name: Java Maven CI

on:
  pull_request:
    branches: [ master ]
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - master # master
      - 'dev-*' # dev-new, dev-this-is-new
      - 'hotfix/**' #hotfix/new hotfix/new/button
      # branch developer-1 wouldn't start workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional